version: '3'
services:
  nodejs-app:
    build:
      context: ./nodejs-app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    logging:
      driver: loki
      options:
        loki-url: http://loki:3100/loki/api/v1/push

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-loki-datasource
    depends_on:
      - loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command:
      - -config.file=/etc/promtail/docker-config.yaml
    depends_on:
      - loki
    networks:
      - loki

networks:
  loki:
